version: 2
updates:
  # Frontend: npm dependabot
  - package-ecosystem: "npm"
    directory: "/frontend-vite"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(frontend)"

  # Backend: Maven dependabot 
  - package-ecosystem: "maven"
    directory: "/backend-spring"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(backend)"
