name: e2e-testing CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    environment: .env

    services:
      postgres:
        image: postgres:15
        ports: [5432:5432]
        env:
          POSTGRES_USER: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          POSTGRES_DB: CourseCompass

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build and Start Spring Boot Backend
        run: |
          cd backend-spring
          ./mvnw clean package -DskipTests
          java -jar target/*.jar &
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          TEST_KEY: ${{ secrets.TEST_KEY }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.0.1

      - name: Install frontend dependencies
        run: |
          cd frontend-vite
          npm ci

      - name: Start Vite frontend
        run: |
          cd frontend-vite
          npm run dev &
        env:
          VITE_REDIRECT_URI: http://localhost:5173
          VITE_CLIENT_ID:  ${{ secrets.VITE_CLIENT_ID }}
          VITE_LOCAL_HOST: http://localhost:8080
          VITE_RENDER_BACKEND: https://coursecompass-demo.onrender.com/api/auth/login
          VITE_TEST_KEY: ${{ secrets.VITE_TEST_KEY }}

      - name: Wait for servers
        run: npx wait-on http://localhost:5173 http://localhost:8080

      - name: Install Playwright
        run: npx playwright install

      - name: Run E2E tests
        run: |
          cd frontend-vite
          npm run test:e2e
