name: frontend-vite CI

on:
  push:
    paths:
      - 'frontend-vite/**'
  pull_request:
    paths:
      - 'frontend-vite/**'
  workflow_dispatch:

jobs:
  vitest:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend-vite

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.0.1
          cache: 'npm'
          cache-dependency-path: frontend-vite/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Vitest
        run: npm run test
